sudo: false
language: rust
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls

# run builds for all the trains (and more)
rust:
  - nightly
  - beta
  - stable

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc
after_success:
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  - travis-cargo --only stable doc-upload
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - travis-cargo coveralls --no-sudo --verify

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    # encrypted github token for doc upload (see `GH_TOKEN` link above)
    - secure: "E/lpik6WwpjgXCfwX8ss//bQs2PUeIdvaErtF+lM2SRJGW/62EfVajOl5z0pGyr7rD/bQw1zKZRNctfWMHz0WxLK6qOiSDSkfVhKAVHy0rgAWnxQ4V3i2K0yGvWXBNZi4BxjIS87HWzdUhTEdmj3YdbcP/jvtc/2RHzXyXudelT2oH653QIM4/wCiPrwfIP1yFa0w8iaBS0o1pwOIrdI7qankWxOv9PQoPzboxDrRrLeuAAA14qfcTPsWr2y5tdtrFRjdXyv/hyts2FSJopXULXj17CODNjYgWx/ugxxDQ3Q2UMlRWV5HqAhzrdKhyzawrqF+rM2wlAbWtbYSZfvjKK0g2PD8HjgqAZXvetI9fXtb3FBY+Mrb8xGRO6JuLpxK2UWzBE11rpmcQFQG69J3W1J9aJU7/9fLe1h4OnkSZRQrSZ2lD0DZV2q0RkRxJbaXyok6+GITX1zAqs0tDaINPKQDIyzSQvix/N1QEenxoaddj/ruLcTbR3eSWL7HIV7KNjnXhkEmfnicNomLt9GrKeJGt5t9HiQwldrk0+IJbVwjiw4ADV2scFV/LCRo0GWltV+oDX4JJSYlRUjLOclfan+yeEaTtWTIhr9PBvNMmRoCtF9DgIzXLzcLCriY8QAYflGH6sgKmYG8Se+V7KKM1p/y1oPJjO++dOmZzvu51Q="
